#!/bin/bash

SCRIPT_DIR="`dirname \"$0\"`"

function pause() {
   read -p "$*"
}

source $SCRIPT_DIR/set-env.sh

set -e

support/package_icu
support/package_nginx
support/package_libmcrypt
support/package_libmemcached
support/package_newrelic
echo 'Now upload built packages to Amazon EC2 and make them public'
pause 'Press [Enter] key to continue...'
support/package_php

md5sum *.tar.gz > manifest.md5sum